FROM python:3.12-slim

RUN apt-get update && apt-get install -y build-essential libpq-dev libpq5 && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade setuptools poetry pyopenssl

WORKDIR /app

COPY poetry.lock pyproject.toml ./
COPY demo demo/
COPY demo/.env.demo .env

RUN poetry config virtualenvs.create false && \
    poetry install --only demo --no-interaction --no-ansi --no-root

EXPOSE 7860

CMD ["python", "-u", "demo/ui.py"]
